version: 2.0

workspace: &workspace
  ~/project

config_android: &config_android
  docker:
    - image: circleci/android:api-28
  working_directory: *workspace
  environment:
    JAVA_TOOL_OPTIONS: "-Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Dkotlin.incremental=false"
    TERM: dumb

cache_key: &cache_key
  jars-{{ checksum "build.gradle.kts" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "buildSrc/src/main/java/com/nimroddayan/buildsrc/dependencies.kt"}}

restore_cache: &restore_cache
  restore_cache:
    key: *cache_key

save_cache: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - ~/.gradle

jobs:
  build_debug:
    <<: *config_android
    steps:
      - checkout
      - <<: *restore_cache
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - run:
          name: Assemble
          command: ./gradlew assembleDebug --stacktrace
      - <<: *save_cache
      - store_artifacts:
          path: app/build/outputs
          destination: outputs

  check:
    <<: *config_android
    steps:
      - checkout
      - <<: *restore_cache
      - run:
          name: Lint and Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit    

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_debug
      - check
